### ISSUE TITLE
Upgrade Node to comply with GitHub Action Requirements

### ISSUE THREAD

**Issue by medert** [devil1991/shopify-dupliate-theme#39]
Hey @devil1991 

We are experiencing error on GitHub action due to Node 16 depreciation.
This package is using Node16, can we consider upgrading it to Node18?

![image](https://github.com/devil1991/shopify-dupliate-theme/assets/13491183/78213134-0acf-4a81-94da-18a88f2a8d02)

**Comment by devil1991** [comment]
Thanks @medert , fixed on 1.4.3 https://github.com/devil1991/shopify-dupliate-theme/releases/tag/v1.4.3 please update it on the action where you are getting the error
